src/Zadatak3/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Zadatak3.GuidExtensions;
using Zadatak3.Models.Models;
using Zadatak3.Services.Interfaces;
using Zadatak3.ViewModels;

namespace Zadatak3.Controllers
{
    [Authorize]
    public class ToDoController : Controller
    {
        private IToDoService _toDoService;
        private IUserService _userService;

        public ToDoController(IToDoService toDoService, IUserService userService)
        {
            _toDoService = toDoService;
            _userService = userService;
        }

        [HttpPost]
        [Route("Add")]
        public async Task<ActionResult> Add(AddToDoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = await _userService.GetUserIdAsync(HttpContext.User);

                var toDoItem = new ToDoItem
                {
                    Id = Guid.NewGuid().GenerateSequentialGuid(),
                    UserId = userId,
                    Name = model.Name,
                    Description = model.Description,
                    Status = model.Status,
                    Start = model.Start,
                    Deadline = model.Deadline
                };

                await _toDoService.AddAsync(toDoItem);
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        [Route("Add")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public async Task<List<ToDoItem>> GetAll()
        {
            return await _toDoService.GetAllAsync();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Zadatak3/ViewComponents/DisplayItemViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Zadatak3.Services.Interfaces;

namespace Zadatak3.ViewComponents
{
    public class DisplayItemViewComponent : ViewComponent
    {
        private IToDoService _toDoService;
        private IUserService _useService;

        public DisplayItemViewComponent(IToDoService toDoService, IUserService userService)
        {
            _toDoService = toDoService;
            _useService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (!User.Identity.IsAuthenticated)
                return View("NotLoggedIn");

            var userId = await _useService.GetUserIdAsync(HttpContext.User);

            var items = await _toDoService.GetAllByUserIdAsync(userId);

            //var items = await _toDoService.GetItemsDescending();

            if (items.Count == 0)
                return View("NoItems");

            return View("Items", items);
        }
    }
}

src/Zadatak3/Views/ToDo/Add.cshtml
@model AddToDoViewModel

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
            <form method="post" class="form-horizontal well addform" asp-controller="ToDo" asp-action="Add">
                <div asp-validation-summary="ModelOnly"></div>
                <fieldset class="legend-brdr-bttm">
                    <legend class="textcenter">Add Todo</legend>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label asp-for="Name"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                <input asp-for="Name" class="form-control" placeholder="Name" />
                            </div>
                            <span asp-validation-for="Name" class="text-warning"></span>
                        </div>
                        <div class="col-sm-6">
                            <label asp-for="Status"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-th-list"></i></span>
                                <select asp-for="Status" class="form-control">
                                    <option value="1">To Do</option>
                                    <option value="2">In progress</option>
                                    <option value="3">Done</option>
                                </select>
                            </div>
                            <span asp-validation-for="Status" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label asp-for="Start"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                <input asp-for="Start" class="form-control start" />
                            </div>
                            <span asp-validation-for="Start" class="text-warning"></span>
                        </div>
                        <div class="col-sm-6">
                            <label asp-for="Deadline"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                <input asp-for="Deadline" class="form-control"/>
                            </div>
                            <span asp-validation-for="Deadline" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="col-sm-2"></label>
                        <div class="col-sm-12">
                            <textarea asp-for="Description" class="form-control" placeholder="Description"></textarea>
                            <span asp-validation-for="Description" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-4">
                            <button type="submit" class="btn btn-success">Add</button>
                        </div>
                        <div class="col-xs-4">
                            <a asp-controller="ToDo" asp-action="Index" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>

src/Zadatak3/Views/ToDo/Index.cshtml
<div class="container">
    <div class="row">
        <vc:display-item></vc:display-item>
    </div>    
</div>