src/Zadatak3/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Zadatak3.GuidExtensions;
using Zadatak3.Models.Models;
using Zadatak3.Services.Interfaces;
using Zadatak3.ViewModels;

namespace Zadatak3.Controllers
{
    [Authorize]
    public class ToDoController : Controller
    {
        private IToDoService _toDoService;
        private IUserService _userService;

        public ToDoController(IToDoService toDoService, IUserService userService)
        {
            _toDoService = toDoService;
            _userService = userService;
        }

        [HttpPost]
        [Route("Add")]
        public async Task<ActionResult> Add(AddToDoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = await _userService.GetUserIdAsync(HttpContext.User);

                var toDoItem = new ToDoItem
                {
                    Id = Guid.NewGuid().GenerateSequentialGuid(),
                    UserId = userId,
                    Name = model.Name,
                    Description = model.Description,
                    Status = model.Status,
                    Start = model.Start,
                    Deadline = model.Deadline
                };

                await _toDoService.AddAsync(toDoItem);
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        [Route("Add")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public async Task<List<ToDoItem>> GetAll()
        {
            return await _toDoService.GetAllAsync();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Zadatak3/ViewComponents/LoginStatusViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Zadatak3.Services.Interfaces;

namespace Zadatak3.ViewComponents
{
    public class LoginStatusViewComponent : ViewComponent
    {
        private IUserService _userService;

        public LoginStatusViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userService.GetUserIdAsync(HttpContext.User);

                return View("LoggedIn", user);
            }
            else
            {
                return View("NotLogged");
            }
        }
    }
}

src/Zadatak3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Todo App</title>
   @await Html.PartialAsync("_ScriptStylePartial")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="ToDo" asp-action="Index" class="navbar-brand">Todo App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "ToDo")</li>
                    <li>@Html.ActionLink("Profile", "Profile", "User")</li>
                </ul>
                <vc:login-status></vc:login-status>
            </div>
        </div>
    </div>

    <div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Todo App</p>
        </footer>
    </div>  

    @RenderSection("scripts", required: false)
</body>
</html>

src/Zadatak3/Views/Shared/_ScriptStylePartial.cshtml
<environment names="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/CustomValidation/ToDoStartValidation.js"></script>
    <script src="~/js/CustomValidation/ToDoDeadlineValidation.js"></script>
</environment>
<environment names="Staging,Production">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</environment>
<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>