src/Zadatak3/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Zadatak3.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Please enter your password"), DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter your User Name")]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
    }
}

src/Zadatak3/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Zadatak3.ViewModels
{
    public class RegisterViewModel
    {
        [StringLength(50, ErrorMessage = "Maximum length is 50")]
        [Display(Name = "Adress")]
        public string Adress { get; set; }

        [StringLength(100, ErrorMessage = "Maximum length is 100")]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Confirm password is required"), DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "The password and confirmation do not match")]
        public string ConfirmPassword { get; set; }

        [StringLength(255, ErrorMessage = "Maximum length is 255")]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Please enter your Email")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [StringLength(255, ErrorMessage = "Maximum length is 255")]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [StringLength(255, ErrorMessage = "Maximum length is 255")]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter a password"), DataType(DataType.Password)]
        [Display(Name = "Password")]
        [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$", ErrorMessage = "Your password needs to contain at least 6 characters and at least 1 uppercase and 1 digit")]
        public string Password { get; set; }

        [StringLength(50, ErrorMessage = "Maximum length is 50")]
        [Display(Name = "Postal code")]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "Please enter a User Name")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "The User name must be a minimum length of 5 and a maximum length of 20.")]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }
}

src/Zadatak3/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Zadatak3.GuidExtensions;
using Zadatak3.Models.Models;
using Zadatak3.Services.Interfaces;
using Zadatak3.ViewModels;

namespace Zadatak3.Controllers
{
    [Authorize]
    public class ToDoController : Controller
    {
        private IToDoService _toDoService;
        private IUserService _userService;

        public ToDoController(IToDoService toDoService, IUserService userService)
        {
            _toDoService = toDoService;
            _userService = userService;
        }

        [HttpPost]
        [Route("Add")]
        public async Task<ActionResult> Add(AddToDoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = await _userService.GetUserIdAsync(HttpContext.User);

                var toDoItem = new ToDoItem
                {
                    Id = Guid.NewGuid().GenerateSequentialGuid(),
                    UserId = userId,
                    Name = model.Name,
                    Description = model.Description,
                    Status = model.Status,
                    Start = model.Start,
                    Deadline = model.Deadline
                };

                await _toDoService.AddAsync(toDoItem);
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        [Route("Add")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public async Task<List<ToDoItem>> GetAll()
        {
            return await _toDoService.GetAllAsync();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Zadatak3/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Zadatak3.GuidExtensions;
using Zadatak3.Models.Models;
using Zadatak3.Services.Interfaces;
using Zadatak3.ViewModels;

namespace Zadatak3.Controllers
{
    [AllowAnonymous]
    public class UserController : Controller
    {
        private IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        [Route("Login")]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [Route("Login")]
        public async Task<ActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.PasswordLoginAsync(model.UserName, model.Password, false, false);
                if (result.Succeeded)
                {
                    var user = await _userService.FindByNameAsync(model.UserName);
                    bool isAdmin = await _userService.IsinRoleAsync(user, "Administrator");

                    if (isAdmin)
                    {
                        return RedirectToAction("Index", "Admin", new { area = "Admin" });
                    }
                    else
                    {
                        return RedirectToAction("Index", "ToDo");
                    }
                }
            }
            ModelState.AddModelError("", "Invalid login");
            return View(model);
        }

        [HttpPost]
        [Route("Logout")]
        public async Task<ActionResult> Logout()
        {
            await _userService.LogOffAsync();
            return RedirectToAction("Index", "ToDo");
        }

        [HttpGet]
        [Route("Profile")]
        public ActionResult Profile()
        {
            return View();
        }

        [HttpGet]
        [Route("Register")]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [Route("Register")]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newUser = new User
                {
                    Id = Guid.NewGuid().GenerateSequentialGuid(),
                    UserName = model.UserName,
                    Email = model.Email,
                    UserProfile = new UserProfile
                    {
                        Adress = model.Adress,
                        City = model.City,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        Country = model.Country,
                        PostalCode = model.PostalCode
                    }
                };

                var result = await _userService.RegisterAsync(newUser, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Login", "User");
                }
            }
            return View();
        }
    }
}

src/Zadatak3/ViewComponents/UserProfileViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Zadatak3.Services.Interfaces;

namespace Zadatak3.ViewComponents
{
    public class UserProfileViewComponent : ViewComponent
    {
        private IUserService _userService;

        public UserProfileViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = await _userService.GetUserIdAsync(HttpContext.User);

                var model = await _userService.GetCurrentUserProfileAsync(userId);

                return View("UserProfile", model);
            }
            else
            {
                return View("NotLogged");
            }
        }
    }
}

src/Zadatak3/Views/User/Login.cshtml
@model LoginViewModel

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
            <form class="form-horizontal well loginform" method="post" asp-controller="User" asp-action="Login">
                <div asp-validation-summary="ModelOnly"></div>
                <fieldset class="legend-brdr-bttm">
                    <legend class="textcenter">Login</legend>

                    <div class="form-group">
                        <label asp-for="UserName" class="col-sm-3 control-label"></label>
                        <div class="col-xs-12 col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input asp-for="UserName" class="form-control" placeholder="Enter user name" />
                            </div>
                            <span asp-validation-for="UserName" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="col-sm-3 control-label"></label>
                        <div class="col-xs-12 col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input asp-for="Password" class="form-control" placeholder="Enter password" />
                            </div>
                            <span asp-validation-for="Password" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <button type="submit" class="btn btn-success">Login</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>   
</div>

src/Zadatak3/Views/User/Profile.cshtml
<div class="container">
    <div class="row">
        <vc:user-profile></vc:user-profile>
    </div>
</div>

src/Zadatak3/Views/User/Register.cshtml
@model RegisterViewModel

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
            <form class="form-horizontal well registerform" method="post" asp-controller="User" asp-action="Register">
                <div asp-validation-summary="ModelOnly"></div>
                <fieldset class="legend-brdr-bttm">
                    <legend class="textcenter">Register</legend>
                    <div class="form-group">
                        <label asp-for="UserName" class="col-sm-4"></label>
                        <div class="col-sm-8">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input asp-for="UserName" class="form-control" placeholder="User name" />
                            </div>
                            <span asp-validation-for="UserName" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="col-sm-4"></label>
                        <div class="col-sm-8">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                <input asp-for="Email" class="form-control" placeholder="Email" />
                            </div>
                            <span asp-validation-for="Email" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="col-sm-4"></label>
                        <div class="col-sm-8">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input asp-for="Password" class="form-control" placeholder="Password" />
                            </div>
                            <span asp-validation-for="Password" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword" class="col-sm-4"></label>
                        <div class="col-sm-8">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input asp-for="ConfirmPassword" class="form-control" placeholder="Confirm Password" />
                            </div>
                            <span asp-validation-for="ConfirmPassword" class="text-warning"></span>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="legend-brdr-bttm">
                    <legend class="textcenter">Optional</legend>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label asp-for="FirstName"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input asp-for="FirstName" class="form-control" placeholder="First Name" />
                            </div>
                            <span asp-validation-for="FirstName" class="text-warning"></span>
                        </div>
                        <div class="col-sm-6">
                            <label asp-for="LastName"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input asp-for="LastName" class="form-control" placeholder="Last Name" />
                            </div>
                            <span asp-validation-for="LastName" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label asp-for="Adress"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                                <input asp-for="Adress" class="form-control" placeholder="Adress"/>
                            </div>
                            <span asp-validation-for="Adress" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label asp-for="City"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                                <input asp-for="City" class="form-control"  placeholder="City"/>
                            </div>
                            <span asp-validation-for="City" class="text-warning"></span>
                        </div>
                        <div class="col-sm-6">
                            <label asp-for="PostalCode"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                                <input asp-for="PostalCode" class="form-control" placeholder="Postal Code"/>
                            </div>
                            <span asp-validation-for="PostalCode" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label asp-for="Country"></label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-flag"></i></span>
                                <input asp-for="Country" class="form-control" placeholder="Country"/>
                            </div>
                            <span asp-validation-for="Country" class="text-warning"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-4">
                            <button type="submit" class="btn btn-success">Register</button>
                        </div>
                        <div class="col-xs-4">                            
                            <a asp-controller="ToDo" asp-action="Index" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>